include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Build
    - "build/**"
    # Tests
    - "test/**.mocks.dart"
    - ".test_coverage.dart"
    - "coverage/**"
    # Assets
    - "assets/**"
    # Generated
    - "**.g.dart"
    - "**.gql.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.gen.dart"
    - "**.pb.dart"
    - "**.pbenum.dart"
    - "**.pbjson.dart"
    # Flutter Version Manager
    - ".fvm/**"
    # Tools
    - "scripts/**"
    - ".dart_tool/**"
    # Platform
    - "ios/**"
    - "android/**"
    - "web/**"
    - "macos/**"
    - "windows/**"
    - "linux/**"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Always
    always_declare_return_types: true
    always_use_package_imports: true
    always_require_non_null_named_parameters: true
    # Avoid
    avoid_multiple_declarations_per_line: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_relative_lib_imports: true
    avoid_unnecessary_containers: true
    avoid_returning_null_for_future: true
    avoid_dynamic_calls: true
    avoid_init_to_null: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_void_async: true
    # Prefer
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_single_quotes: true
    prefer_asserts_with_message: true
    prefer_final_locals: true
    prefer_typing_uninitialized_variables: true
    # Other
    file_names: true
    camel_case_extensions: true
    camel_case_types: true
    exhaustive_cases: true
    no_duplicate_case_values: true
    cancel_subscriptions: true
    close_sinks: true
    invalid_case_patterns: true
    await_only_futures: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    curly_braces_in_flow_control_structures: true
    type_init_formals: true
    sort_child_properties_last: true
    no_leading_underscores_for_local_identifiers: true
    sort_constructors_first: true
    require_trailing_commas: true
    unawaited_futures: true
