name: totp_authenticator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  base32: ^2.1.3
  crypto: ^3.0.5
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.0
  provider: ^6.1.2
  flutter_expandable_fab: ^2.3.0
  mobile_scanner: ^6.0.0
  totp: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
